from ubuntu:16.04

#apt-key adv --keyserver pgp.mit.edu --recv-key 6CD895FFA313E824
RUN apt-get update \
 && apt-get install -y apt-transport-https x11vnc xvfb

 #add emergent repo and install
 #RUN echo 'deb https://grey.colorado.edu/ubuntu xenial main' >> /etc/apt/sources.list
 #RUN apt-get update -o Acquire::https::grey.colorado.edu::Verify-Peer=false
 #RUN apt-get install -y --allow-unauthenticated emergent=8.0.0-9984ubuntu1 -o Acquire::https::grey.colorado.edu::Verify-Peer=false

#build from source
ARG emer_rev=8966
RUN apt-get install -y wget qt5-default qttools5-dev libqt5webkit5-dev qtlocation5-dev libqt5designer5 qtdeclarative5-dev libqt5sensors5-dev qtmultimedia5-dev libqt5svg5-dev libcoin80-dev cmake g++ libreadline6-dev libgsl0-dev zlib1g-dev libpng12-dev libjpeg-dev libncurses5-dev libsvn-dev libsndfile1-dev mercurial python-pip subversion devscripts csh pkg-config libode-dev

RUN svn checkout --trust-server-cert --non-interactive -r $emer_rev https://grey.colorado.edu/svn/emergent/emergent/trunk /emergent

#make svn checkout loose
#RUN sed -i 's/svn co/svn co --trust-server-cert --non-interactive/g' /emergent/package/ubuntu-motu-quarter
#RUN /emergent/package/ubuntu-motu-quarter
RUN  wget --no-check-certificate  https://grey.colorado.edu/ubuntu/dists/xenial/main/binary-amd64/libquarter0_1.0-0ubuntu1_amd64.deb
RUN dpkg -i libquarter0_1.0-*ubuntu1_*.deb
RUN rm libquarter0_1.0-*ubuntu1_*.deb


#see https://grey.colorado.edu/pipermail/emergent-users/2016-July/002924.html
RUN sed -i 's/#define dSINGLE//g' /emergent/src/temt/ta_core/ta_stdef.h
ENV /usr/include/x86_64-linux-gnu/qt5
WORKDIR /emergent
RUN ./configure --qt5 --clean --webkit
WORKDIR /emergent/build
RUN make -j4
RUN make install

ENV PATH=/bin:/usr/bin:/usr/local/bin
ENV LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib


CMD ["x11vnc","-create","-forever"]


